megastep/makeself

- README.md
- makeself.sh
This commit modifies the --encrypt argument to --gpg-encrypt and adds an --ssl-encrypt option. 
The openssl encrypt option will prompt for a passphrase on encrypt and on decrypt. 
I have tested this on linux and osx. This is a crossplatform encryption solution :)
> adding ssl support

- makeself.sh
The options added for --follow had something after the "f", which caused
the "h" to be interpreted as a filename. Fixed by moving the "f" to be
the last option in TAR_ARGS.
> Fixing tar --follow option breaking

- makeself-header.sh
Currently the following scenario is broken:
developer@dev-machine$ makeself.sh --notemp app/ app.run app
...
root@user-machine# cd /opt && ~/Downloads/app.run
user@user-machine$ /opt/app/bin/app
bash: /opt/app/bin/app: Permission denied
The problem is that users on user-machine cannot access unpacked files,
since they are created with umask 077.
The proposed solution is to use the original umask for untar.
> set original permissions for unpacked files

- README.md
The name of "Return To Castle Wolfenstein" is misspelled.
> Typo in readme file

- README.md
The readme suggests that it's optional to use the `--` to cause additional parameters to be passed to the underlying script. However, it seems required based on looking at the code and the comments therein.
> Correct readme wording

- .gitmodules
- README.md
- makeself.1
- makeself.sh
- test/datetest
Enable setting of package date, so the package can be create multiple times from source and have byte for byte identical packages.
Needed when the package is part of a reproducible build.
> --packaging-date

- README.md
* Add an example usage of `--tar-extra` to README.
* Fix #53.
Signed-off-by: mr.Shu <mr@shu.io>
--------------------------------------
@megastep I am not sure if you are OK with this, but I also ran into #53 today, and thought it may be better to add an explicit example to `README`.
Please feel free to do whatever with this PR.
> README: Add example for --tar-extra

- makeself.sh
This PR adds support for asymmetric encryption and signing with GPG.  It also provides an extra option --gpg-extra to pass in additional information such as recipients and default keys etc.  This also adds quotes to $TAR_EXTRA in order to support complex options with spaces, such as "--use-compress-program=xz -e -T 0 -9"  This allows for maximum compression with xz and gpg encryption and signing.  One use case of this would be:  `./makeself.sh --gpg-asymmetric-encrypt-sign --complevel 0 --gpg-extra "--default-key XXXXXX -r XXXXXX --local-user XXXXXX"  --tar-extra "--use-compress-program=xz -e -T 0 -9" ./test_install/ test.run "Test Header" ./install.sh`
> Add --gpg-extra and --gpg-aysmmetric-encrypt-sign

- makeself-header.sh
- makeself.sh
Add support for an additional command line flag --untar-extra which is able to pass arbitrary arguments to tar during the UnTar command.  My use case is: ./makeself.sh --gpg-asymmetric-encrypt-sign --complevel 0 --gpg-extra "--default-key XXXXXX -r XXXXXX --local-user XXXXXX" --tar-extra "--use-compress-program=xz -e -T 0 -9" --untar-extra "-J" ../things  Things.run  "\n Things.run \n" ./install.sh
> Add --untar-extra

- makeself-header.sh
Hi,
thank you for makeself! Impressive work!
I use it at [netdata](https://github.com/firehol/netdata) to distribute static binaries of it.
Users [have asked](https://github.com/firehol/netdata/issues/2305) for it to be installed without any user interaction. However `makeself-header.sh` did not provide an option to accept the license from the command line. So, I added option `--accept` to allow the users accept the license from the command line.
This is usefull in automated scripts. With the evolution of automated deployment tools (ansible, chef, puppet, salt, etc), this kind of non-interactive installation is increasingly handy.
> allow the users to accept the license from the command line 

- makeself-header.sh
Out of curiosity, I mv'ed tar for a while and run my program ./repo
created with makeself to see what would happen.  I noticed that
`Extraction failed' part is not well readable so I decided to make
this little patch to fix it.
> Prepend error message in UnTAR() with `...' to make it more readable

- makeself-header.sh
Address issue #106. This should still work with the added UNTAR_EXTRA feature, but returns to the known-working tar invocation for rickety old Solaris.
I took the liberty of dropping an extra empty line and the quotes around UNTAR_EXTRA so as to preempt any multi-arg problems.
> Return to tar args that work for Solaris

- makeself.sh
Hi @megastep 
This PR fixes regression made after release [2.3.0](https://github.com/megastep/makeself/tree/release-2.3.0).
Previously it was possible to specify multiple `tar` options like this:
```bash
makeself.sh --bla --bla --tar-extra "--tar-opt-1 --tar-opt-2" archive_dir ...
```
Now that is broken by #98. Following changes will bring back the functionality available in release `2.3.0`.
Thanks for this awesome tool.
> Fix `--tar-extra` to accept multiple tar options

- .travis.yml
- test/tarextratest
This PR is a follow-up for #108. It adds unit test for preventing further regressions.
The test is compatible with GNU and BSD `tar` implementations.
> Add unit test for `--tar-extra` option

- makeself-header.sh
- makeself.sh
I stumbled into the same issue #82 user @nmontmarquette tried to solve in pull request #83. This is a more portable fix that escapes all characters having a special meaning in double quotes; hopefully I got all of them…
> Improve handling of complex license texts

- makeself-header.sh
- makeself.sh
a) Support alternate password source for openssl encrypt
b) A couple of fixes to make openssl decryption work in default Solaris 10 install (OpenSSL 0.9.7d)
> Openssl improvements

- makeself-header.sh
- makeself.sh
This PR allows scripts encoded with `base64` to be extracted on Linux and MacOS X.
I have created a makeself archive in Linux, but unable to extract it on MacOS X:
```
$ ./archive.run --target tmp
Creating directory tmp
Verifying archive integrity...  100%   All good.
Uncompressing archivebase64: invalid option -- d
Usage:    base64 [-hvD] [-b num] [-i in_file] [-o out_file]
-h, --help     display this message
-D, --decode   decodes input
-b, --break    break encoded string into num character lines
-i, --input    input file (default: "-" for stdin)
-o, --output   output file (default: "-" for stdout)
Extraction failed.
```
Used common long option `--decode` of `base64` utility and explicitly read from `stdin`.
> Support base64 decoding on MacOS X

- makeself-header.sh
- makeself.sh
Plus assorted minor improvements.
The main effect of this PR is that OpenSSL encryption is now applied on top of compression, whereas previously it was synonymous with no compression. I contemplated adding yet another command line option to work around this behavior change but then decided that in the end, compression is a Good Thing and if some users want to encrypt their archives without compressing they can use `--nocomp` option explicitly instead of relying on a unintended side effect of previous implementation.
That said, while I see this as a minor breaking change it is still a change. If you think it is a Bad Thing I'm open to working around this issue.
> Support OpenSSL encryption with compression (not instead of)

- makeself-header.sh
On NixOS (a Linux distribution), there is no `/bin/rm`, but an `rm` command will generally be available in one's path when running shell scripts.  Here, I change a couple of invocations of `/bin/rm` into invocations of `rm` to deal with this issue.
Since `rm` is already called elsewhere in the script without an absolute path, I assume this change will not cause any regressions.  Still, I've tested this on a CentOS machine and a NixOS machine, though not other platforms.
> Use `rm` from PATH

- test/appendtest
- test/extracttest
- test/tarextratest
an "assert $?" really just says "assert 1" (or some non-zero number) on a failure. Bashunit treats this as a success. This fixes them so it checks is the return value is 0.
This also adds a test to for the --append argument, which also fails, as seen in #48 It doesn't fix the issue, I may or may not be able to do that
> Fix unit tests so they fail when there are failures

- makeself.sh
After `cd`-ing to `$archdir`, use `find` and `sort` to generate a [stable order
of inputs][0] (in the form of a newline-delimited list of paths) from which
`tar` reads via `-T-`.
This feature depends on `tar` support for the `-T` option as well as the
presence of the commands `find` and `sort`.
[0]:https://reproducible-builds.org/docs/stable-inputs/
> stable order inputs: find, sort, tar -T

- makeself-header.sh
The option --accept was introduced to support automated scripts. As our software license is quite long it will be shown page by page, where space need to be pressed to continue with the next page. This is extremely helpful, when the user has to accept the license himself.
However in cases of automated scripts this is not working. Therefore I have introduced a change, that when the --accept option which was introduced in #100 is used, that the license is shown completely without having to press any additional button.
> disable showing license page by page when --accept option is used

- .travis.yml
- makeself.sh
- test/whitespacetest
* don't use `xargs -0` because it's not well supported
* use `sed 's/./\\&/g'` to properly quote whitespace in paths
* add test unit for whitespace-containing paths
This patch addresses comments made in github pull request #151 regarding
whitespace-containing filenames and stable sorted inputs.
References on lacking `xargs -0`:
* http://nixdoc.net/man-pages/HP-UX/man1/xargs.1.html
* http://nixdoc.net/man-pages/IRIX/man1/xargs.1.html
* http://nixdoc.net/man-pages/Tru64/man1/xargs.1.html
* https://www.unix.com/man-page/sunos/1/xargs
References on using find with xargs:
* http://www.etalabs.net/sh_tricks.html
> stable sort, even with whitespace paths

- makeself-header.sh
- makeself.sh
- test/appendtest
Uncompresses the original archive into the temporary location before attempting to append files to the tar. Tar is incapable of directly appending files to a compressed archive.
Removes broken and unnecessary references to the original checksums.
> Fix #48 --append functionality

- makeself-header.sh
This should solve #134 .
It also makes sure the script parameters are passed-through correctly. (i tested it by using --confirm with both gnome-terminal and xterm)
(a perfect regression test would test the installer against every supported terminal.)
> Removed -title since its not compatible with all terminal types.

- makeself.sh
Remove the `! -type d` search parameters from the `find` call and replace it with `-mindepth 1`.
Sole effect should be to include empty directories within the target tree in the self-extracting archive.
> Include empty dirs in archive -- Fix #175

- makeself-header.sh
Added `RUNNING_DIR` env variable which exposes the dirname of the makeself executable for startup scripts.
> Expose dirname of makeself executable

- makeself.sh
- test/whitespacelicense
Printing path to the file instead of content of the file was introduced
in 56c742bd90ebcb22feaff4d78ae4e62e72ffc7ad
Reverting parsing of the license file to the way it was before that
commit and escaping argument with quotes to address the original issue
> Printing content of license file (#197)

- README.md
- makeself-header.sh
- makeself.1
- makeself.sh
Use case example:
During execution a temporary Docker image is loaded and started, but
must be stopped and removed before returning to the controlling
terminal. Since this must happen in both exit cases (normal exit, and
signal capture handling) and since `trap` handling does not appear to work inside
`startup_script`, an alternative is needed.
Specifying `makeself ... --cleanup ./cleanup.sh ...` allows using an
included script to stop and remove the image in both situations.
The cleanup script is provided the same arguments that are given to
`startup_script` and is executed from the same working directory.
> Add cleanup script via `--cleanup file` argument

- README.md
- makeself-header.sh
Using the `$@` arguments seems to be problematic when trying to preserve
whitespace, so instead use a separate source for the arguments if
necessary.
See comments on #201 for reference.
> Use `--cleanup-args` when executing cleanup script

- makeself-header.sh
No point in running cleanup if nothing was executed.
> Make `--noexec` also apply to the cleanup script

- makeself.sh
- test/appendtest
This should restore `--append` to its working test. Further, the `appendtest` will now detect similar issues
Closes #216
> Fix append

- makeself-header.sh
- test/variabletest
I noticed that `ARCHIVE_DIR` was missing some quotes, so I added a unit test and solution for this.
I wasn't sure how you want the final quotes to be, it seemed a little inconsistent, so I just left them alone. I always prefer to put the quotes in, but that's just my style.
```bash
CRCsum="$CRCsum"
MD5="$MD5sum"
SHA="$SHAsum"
TMPROOT=\${TMPDIR:=/tmp}
USER_PWD="\$PWD"
export USER_PWD
ARCHIVE_DIR=\`dirname "\$0"\`
export ARCHIVE_DIR
```
Could become
```bash
CRCsum="$CRCsum"
MD5="$MD5sum"
SHA="$SHAsum"
TMPROOT="\${TMPDIR:=/tmp}"
USER_PWD="\$PWD"
export USER_PWD
ARCHIVE_DIR="\`dirname "\$0"\`"
export ARCHIVE_DIR
```
However the $0 _required_ quotes to work in situations where the directory had white space in it.
I can add the more quotes if you prefer. Just let me know!
> Fix archive dir

- makeself-header.sh
Some dd implementations may lack some features. The most prominent is
busybox configured with a minimal subset of dd. This minimal
configuration is sometimes used with Yocto/OpenEmbedded systems and
seems to be the default configuration.
Check dd for these features by executing dd, reading /dev/zero and
writing to /dev/null with the ibs, obs and conv options. Use the
block/bytes writing scheme in success and a simpler dd call otherwise.
This commit fixes megastep/makeself#161.
> Test dd features before executing

- makeself.sh
- test/appendtest
The decompression command specified by `--compress` does not match the
semantics required by the `--append` operation. Change the decompression
command for the `--compress` to match those of the other compression options.
edit `makeself.sh`:
* try to locate `gzip` and `compress` commands and set the `COMPRESS` variable
appropriately. Change `COMPRESS` value for `compress` from `Unix` to
`compress`.
* change switch block to match new value
* change `GUNZIP_CMD` from `exec` expression to `uncompress -cf`
edit `test/appendtest`:
* be clever with the way we setup the test archives
* test every compression option, if we have the required command
> fix #231: get --append working with --compress

- makeself.sh
Zstd supports `--threads` since version 1.2.0 (May 2017) according to https://github.com/facebook/zstd/blob/dev/CHANGELOG
Setting `--threads 0` greatly improves compression times.
> Pass threads option to zstd compressor

- makeself.sh
- test/lsmtest
* edit `makeself.sh`: change the LSM_CMD from `cat` to `awk 1` when generating
the LSM content into the archive
* add `test/lsmtest`: verify the correct functionality of three different LSM
files; i.e., empty, single line, and single line without trailing newline.
> fix #254: allow and sanitize lsm files without trailing newlines

- test/signtest
update `test/signtest` with the following improvements:
* add function `cat_key` to manage secret keys as heredocs of ascii-armored
content
* add function `checked_import_key` to manage/verify secret key imports
* add function `create_sign_verify` to create, sign, and verify signatures on
makeself archives
* remove the two existing tests and add four new tests:
* `testSingleKey`: test simple sign/verify with one existing key
* `testMultipleKeys`: test more complicated sign/verify when more than one
key is present (this would have caught issue #257)
* `testWrongKey`: ensure that using the wrong key fails signature
verification
* `testWrongPassword`: ensure that using the wrong password fails to create a
signature
> signtest: more and better

- makeself-header.sh
Because VMware ESXi version 6.5 ships 'df' as a (very) non-compliant python script that (surprise) doesn't support your fancy POSIX output format.
Further reading:
* https://git.busybox.net/busybox/tree/coreutils/df.c
* https://github.com/landley/toybox/blob/master/toys/posix/df.c
* https://pubs.opengroup.org/onlinepubs/9699919799/utilities/df.html
> fix 282: 'df -kP' -> 'df -k'

- makeself-header.sh
ESXi v6.5 ships without 'tr'. Within 'makeself-header.sh', replace every instance of
tr -d " "
with
sed "s/ //g"
> fix #282 redux: ESXi workaround: 'tr' -> 'sed'

- makeself-header.sh
Allow for variable usage in helpheader.
Example:
```
3) Additional arguments specific to $label :
--installdir          Set the installation directory
--someflag            Set someflag
--otherflag           Set some other flag
Example:
$0 -- --installdir=~/Applications/MyApp --someflag
```
Note the double empty lines at the start of the file.
> Evaluate variables in helpheader

- README.md
When `--target dir` was added to the `README.md`, it split `--tar-extra` from its example. This PR fixes that.
> Move "--target dir" to after the "--tar-extra" example

- makeself-header.sh
If something if fine, it should not (IMHO) be on stderr. This could cause false alarms to users where makeself is embedded into another installer.
> Changed output from stderr to stdout if the checksum is ok.

- README.md
- makeself.1
- makeself.sh
- test/compextratest
This feature adds a new command line parameter, `--comp-extra`, which functions similarly to `--tar-extra`, in that it allows a user to add extra parameters to whichever compressor they have chosen to use.
The basis for this feature was to allow passing `--no-name` to gzip, as part of a quest to make fully reproducible makeself archives.
> Feature: Allow extra options to compressor

- makeself-header.sh
The dd option skip seeks the input stream. An additional count reads the specified bytes from the input and outputs it. This causes the last bytes read to be incorrect.
> Only skip offset
